-keep class !me.zanghai.android.materialprogressbar.**,** {*;}
-keep class !android.support.v7.view.menu.*MenuBuilder*, android.support.v7.** { *; }
-keep interface android.support.v7.* { *; }
-dontwarn
-ignorewarnings